In [1]:
import pandas as pd
import numpy as np

In [2]:
titanic=pd.read_csv("train5.csv")

In [3]:
type(titanic)

pandas.core.frame.DataFrame

In [4]:
titanic

Pclass                                               Name     Sex    Age  \
0         2      Weisz, Mrs. Leopold (Mathilde Francoise Pede)  female  29.00   
1         3                  Williams, Mr. Howard Hugh "Harry"    male    NaN   
2         2     Morley, Mr. Henry Samuel ("Mr Henry Marshall")    male  39.00   
3         3        Palsson, Mrs. Nils (Alma Cornelia Berglund)  female  29.00   
4         3                             Sutehall, Mr. Henry Jr    male  25.00   
5         3                         Lemberopolous, Mr. Peter L    male  34.50   
6         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.00   
7         3                                 Jonkoff, Mr. Lalio    male  23.00   
8         2                       Williams, Mr. Charles Eugene    male    NaN   
9         3                           Rouse, Mr. Richard Henry    male  50.00   
10        3                    Stanley, Miss. Amy Zillah Elsie  female  23.00   
11        3                                  Kassem, Mr. Fared    male    NaN   
12        2                            Fox, Mr. Stanley Hubert    male  36.00   
13        3                                  Lennon, Mr. Denis    male    NaN   
14        3                         Healy, Miss. Hanora "Nora"  female    NaN   
15        3                       Gustafsson, Mr. Johan Birger    male  28.00   
16        3                                  Jonsson, Mr. Carl    male  32.00   
17        3                                Abbing, Mr. Anthony    male  42.00   
18        1                          Graham, Mr. George Edward    male  38.00   
19        3                                Jermyn, Miss. Annie  female    NaN   
20        1                    Reuchlin, Jonkheer. John George    male  38.00   
21        3                      Boulos, Mrs. Joseph (Sultana)  female    NaN   
22        2  Watt, Mrs. James (Elizabeth "Bessie" Inglis Mi...  female  40.00   
23        3                      Sawyer, Mr. Frederick Charles    male  24.50   
24        3                            Masselmani, Mrs. Fatima  female    NaN   
25        3                       Sage, Miss. Constance Gladys  female    NaN   
26        1                             Andrews, Mr. Thomas Jr    male  39.00   
27        1                                Ringhini, Mr. Sante    male  22.00   
28        3                             Eklund, Mr. Hans Linus    male  16.00   
29        2                         Matthews, Mr. William John    male  30.00   
..      ...                                                ...     ...    ...   
638       3                               Davies, Mr. Alfred J    male  24.00   
639       2  Laroche, Mrs. Joseph (Juliette Marie Louise La...  female  22.00   
640       3                                 Lefebre, Miss. Ida  female    NaN   
641       3                                Jussila, Mr. Eiriik    male  32.00   
642       1                  Calderhead, Mr. Edward Pennington    male  42.00   
643       3                         Kallio, Mr. Nikolai Erland    male  17.00   
644       1                                Baumann, Mr. John D    male    NaN   
645       2                    Richards, Master. George Sibley    male   0.83   
646       3                   Ford, Miss. Robina Maggie "Ruby"  female   9.00   
647       1                            Kent, Mr. Edward Austin    male  58.00   
648       2                                  Harper, Rev. John    male  28.00   
649       3                                    Adams, Mr. John    male  26.00   
650       3                        Vander Cruyssen, Mr. Victor    male  47.00   
651       3                         Thorneycroft, Mr. Percival    male    NaN   
652       2            West, Mrs. Edwy Arthur (Ada Mary Worth)  female  33.00   
653       3     Robins, Mrs. Alexander A (Grace Charity Laury)  female  47.00   
654       3                                Todoroff, Mr. Lalio    male    NaN   
655       1                       Ki

In [5]:
x_train=titanic.iloc[:,0:10]
y_train=titanic.iloc[:,10]

In [6]:
x_train['Q']=(x_train['Embarked']=='Q').astype(int)
x_train['P']=(x_train['Embarked']=='P').astype(int)
x_train['S']=(x_train['Embarked']=='S').astype(int)
x_train.drop('Embarked',inplace=True,axis=1)
x_train.drop('Name',inplace=True,axis=1)
x_train['Sex']=x_train['Sex'].map({'female':1,'male':0}).astype(int)
x_train.drop('Ticket',inplace=True,axis=1)
x_train.drop('Cabin',inplace=True,axis=1)
x_train.drop('Fare',inplace=True,axis=1)
x_train['family']=x_train['SibSp']+x_train['Parch']+1
x_train.Age.fillna(x_train.Age.mean(),inplace = True)

In [7]:
x_train

Pclass  Sex       Age  SibSp  Parch  Q  P  S  family
0         2    1  29.00000      1      0  0  0  1       2
1         3    0  29.70056      0      0  0  0  1       1
2         2    0  39.00000      0      0  0  0  1       1
3         3    1  29.00000      0      4  0  0  1       5
4         3    0  25.00000      0      0  0  0  1       1
5         3    0  34.50000      0      0  0  0  0       1
6         1    1  35.00000      1      0  0  0  1       2
7         3    0  23.00000      0      0  0  0  1       1
8         2    0  29.70056      0      0  0  0  1       1
9         3    0  50.00000      0      0  0  0  1       1
10        3    1  23.00000      0      0  0  0  1       1
11        3    0  29.70056      0      0  0  0  0       1
12        2    0  36.00000      0      0  0  0  1       1
13        3    0  29.70056      1      0  1  0  0       2
14        3    1  29.70056      0      0  1  0  0       1
15        3    0  28.00000      2      0  0  0  1       3
16        3    0  32.00000      0      0  0  0  1       1
17        3    0  42.00000      0      0  0  0  1       1
18        1    0  38.00000      0      1  0  0  1       2
19        3    1  29.70056      0      0  1  0  0       1
20        1    0  38.00000      0      0  0  0  1       1
21        3    1  29.70056      0      2  0  0  0       3
22        2    1  40.00000      0      0  0  0  1       1
23        3    0  24.50000      0      0  0  0  1       1
24        3    1  29.70056      0      0  0  0  0       1
25        3    1  29.70056      8      2  0  0  1      11
26        1    0  39.00000      0      0  0  0  1       1
27        1    0  22.00000      0      0  0  0  0       1
28        3    0  16.00000      0      0  0  0  1       1
29        2    0  30.00000      0      0  0  0  1       1
..      ...  ...       ...    ...    ... .. .. ..     ...
638       3    0  24.00000      2      0  0  0  1       3
639       2    1  22.00000      1      2  0  0  0       4
640       3    1  29.70056      3      1  0  0  1       5
641       3    0  32.00000      0      0  0  0  1       1
642       1    0  42.00000      0      0  0  0  1       1
643       3    0  17.00000      0      0  0  0  1       1
644       1    0  29.70056      0      0  0  0  1       1
645       2    0   0.83000      1      1  0  0  1       3
646       3    1   9.00000      2      2  0  0  1       5
647       1    0  58.00000      0      0  0  0  0       1
648       2    0  28.00000      0      1  0  0  1       2
649       3    0  26.00000      0      0  0  0  1       1
650       3    0  47.00000      0      0  0  0  1       1
651       3    0  29.70056      1      0  0  0  1       2
652       2    1  33.00000      1      2  0  0  1       4
653       3    1  47.00000      1      0  0  0  1       2
654       3    0  29.70056      0      0  0  0  1       1
655       1    0  42.00000      1      0  0  0  1       2
656       3    0  36.00000      0      0  0  0  1       1
657       3    0  38.00000      0      0  0  0  1       1
658       3    1  38.00000      1      5  0  0  1       7
659       3    0  29.70056      0      0  1  0  0       1
660       2    0   1.00000      2      1  0  0  1       4
661       1    1  29.70056      1      0  0  0  0       2
662       1    0  47.00000      0      0  0  0  1       1
663       2    1  17.00000      0      0  0  0  1       1
664       3    0  29.70056      0      0  1  0  0       1
665       3    0  32.00000      0      0  0  0  1       1
666       3    1  22.00000      0      0  0  0  1       1
667       3    1  29.70056      1      0  1  0  0       2

[668 rows x 9 columns]

In [8]:
from sklearn.linear_model import LogisticRegression

In [9]:
clf=LogisticRegression()

In [122]:
x

array([[2.00000e+00,         nan,         nan, ..., 2.28414e+05,
        2.60000e+01,         nan],
       [3.00000e+00,         nan,         nan, ...,         nan,
        8.05000e+00,         nan],
       [2.00000e+00,         nan,         nan, ..., 2.50655e+05,
        2.60000e+01,         nan],
       ...,
       [3.00000e+00,         nan,         nan, ..., 1.60100e+03,
        5.64958e+01,         nan],
       [3.00000e+00,         nan,         nan, ..., 7.55300e+03,
        9.83750e+00,         nan],
       [3.00000e+00,         nan,         nan, ..., 3.67230e+05,
        1.55000e+01,         nan]])

In [123]:
y

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, na

In [11]:
type(x_train)

pandas.core.frame.DataFrame

In [12]:
type(y_train)

pandas.core.series.Series

In [13]:
clf.fit(x_train,y_train)

C:\Users\Vithal\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [20]:
test=pd.read_csv("test5.csv")
x_test=test.copy()

In [21]:
x_test['Q']=(x_test['Embarked']=='Q').astype(int)
x_test['P']=(x_test['Embarked']=='P').astype(int)
x_test['S']=(x_test['Embarked']=='S').astype(int)
x_test.drop('Embarked',inplace=True,axis=1)
x_test.drop('Name',inplace=True,axis=1)
x_test['Sex']=x_test['Sex'].map({'female':1,'male':0}).astype(int)
x_test.drop('Ticket',inplace=True,axis=1)
x_test.drop('Cabin',inplace=True,axis=1)
x_test.drop('Fare',inplace=True,axis=1)
x_test['family']=x_test['SibSp']+x_test['Parch']+1
x_test.Age.fillna(x_test.Age.mean(),inplace = True)

In [22]:
x_test.shape

(223, 9)

In [23]:
y_pred=clf.predict(x_test)

In [24]:
y_pred

array([0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0], dtype=int64)

In [25]:
y_pred.shape

(223,)

In [26]:
np.savetxt("y_pred6.csv",y_pred)