In [1]:
import pandas as pd
import numpy as np

In [2]:
data=np.loadtxt("train2.csv",delimiter=",")

In [3]:
data

array([[-0.40784991, -0.48772236, -1.2660231 , ...,  0.41057102,
        -1.09799011, 37.9       ],
       [-0.40737368, -0.48772236,  0.24705682, ...,  0.29116915,
        -0.52047412, 21.4       ],
       [ 0.1251786 , -0.48772236,  1.01599907, ..., -3.79579542,
         0.89107588, 12.7       ],
       ...,
       [-0.40831101, -0.48772236,  0.24705682, ...,  0.33206621,
        -0.33404299, 20.8       ],
       [-0.41061997, -0.48772236, -1.15221381, ...,  0.203235  ,
        -0.74475218, 22.6       ],
       [ 0.34290895, -0.48772236,  1.01599907, ...,  0.38787479,
        -1.35871335, 50.        ]])

In [4]:
len(data)

379

In [5]:
data.shape

(379, 14)

In [5]:
def stepgradient(learning_rate,m):
    m_slope=np.zeros(14)
    n=len(data)
    data2=data[:,0:13]
    data3=np.zeros([379,14])
    data3[:,13]=1
    data3[:,0:13]=data3[:,0:13]+data2
    for i in range(n):
        
        x=data3[i]
        y=data[i,13]
        for j in range(14):
            x2=x[j]
            m_slope[j]+=(-2/n)*(y-(m*x).sum())*x2
    new_m=m-learning_rate*m_slope
    return new_m

In [6]:
def gd(learning_rate,num_iterations):
    m=np.zeros(14)
    for i in range(num_iterations):
        m=stepgradient(learning_rate,m)
    return m

In [7]:

learning_rate=0.01
num_iterations=100
m2=gd(learning_rate,num_iterations)

In [8]:
m2

array([-0.71980943,  0.32105184, -0.39782066,  1.07253383, -0.5851858 ,
        3.35680621,  0.10193905, -0.98886677,  0.56281451, -0.22255802,
       -1.66114583,  0.67831581, -3.15805718, 19.60768685])

In [9]:
data5=np.loadtxt("test2.csv",delimiter=",")

In [10]:
n=len(data5)

In [11]:
data5.shape

(127, 13)

In [12]:
data2=data5[:,0:13]
data3=np.zeros([127,14])
data3[:,13]=1
data3[:,0:13]=data3[:,0:13]+data2

In [13]:
ypred=np.zeros(n)
for i in range(n):
    ypred[i]=(data3[i]*m2).sum()

In [14]:
ypred

array([ 7.07168935, 25.41929737, 18.8205551 , 20.98730361, 17.75442298,
        1.68043412, 24.63934979, 20.27982868, 15.676567  , 19.11593718,
       21.35437859, 15.65706979, 17.60982374, 18.96426782, 40.63618   ,
       21.06552584, 20.6831598 , 23.3540473 , 17.72842949, 27.59353439,
       20.33473   , 20.16103222, 28.98406932, 31.89329327, 29.42085079,
       11.6650001 , 17.98997522, 27.89991246, 21.88992017, 30.28976594,
       15.22483867, 21.86867286, 20.6660513 , 22.35459881, 12.8421853 ,
       24.48137232, 22.32921336, 17.43015764, 21.2337052 ,  8.207245  ,
        2.49472247, 24.56787345, 26.00156569, 17.98789946, 17.21200481,
       -0.5692186 , 36.68908115, 22.66841865, 28.31712987, 15.23378271,
       14.29326043, 35.65986307, 15.94449764, 17.03050563, 14.22520306,
       18.20413548, 15.72707221, 19.0347688 , 11.83799673, 14.95624542,
       11.73584817, 25.20700595, 20.92540816, 22.22429249, 13.54761438,
       11.99384938, 30.58167067, 15.03969732, 23.27404379, 18.99

In [16]:
np.savetxt("y_pred1.csv",(ypred))