In [50]:
import pandas as pd
import numpy as np
np.set_printoptions(suppress=True)

In [51]:
data=np.loadtxt("train3.csv",delimiter=",")

In [52]:
data

array([[   8.58,   38.38, 1021.03,   84.37,  482.26],
       [  21.79,   58.2 , 1017.21,   66.74,  446.94],
       [  16.64,   48.92, 1011.55,   78.76,  452.56],
       ...,
       [  29.8 ,   69.34, 1009.36,   64.74,  437.65],
       [  16.37,   54.3 , 1017.94,   63.63,  459.97],
       [  30.11,   62.04, 1010.69,   47.96,  444.42]])

In [53]:
len(data)

7176

In [54]:
data.shape

(7176, 5)

In [55]:
def stepgradient(learning_rate,m):
    m_slope=np.zeros(5)
    n=len(data)
    data2=data[:,0:4]
    data3=np.zeros([7176,5])
    data3[:,4]=1
    data3[:,0:4]=data3[:,0:4]+data2
    for i in range(n):
        
        x=data3[i]
        y=data[i,4]
        for j in range(5):
            x2=x[j]
            m_slope[j]+=(-2/n)*(y-(m*x).sum())*x2
    new_m=m-learning_rate*m_slope
    return new_m

In [56]:
def gd(learning_rate,num_iterations):
    m=np.zeros(5)
    for i in range(num_iterations):
        m=stepgradient(learning_rate,m)
    return m

In [57]:

learning_rate=0.01
num_iterations=50
m2=gd(learning_rate,num_iterations)

In [58]:
m2

array([-5.51420012e+213, -1.52595036e+214, -2.84953049e+215,
       -2.06116860e+214, -2.81213923e+212])

In [59]:
data5=np.loadtxt("test3.csv",delimiter=",")

In [60]:
n=len(data5)

In [61]:
data5.shape

(2392, 4)

In [62]:
data2=data5[:,0:4]
data3=np.zeros([2392,5])
data3[:,4]=1
data3[:,0:4]=data3[:,0:4]+data2

In [63]:
ypred=np.zeros(n)
for i in range(n):
    ypred[i]=(data3[i]*m2).sum()

In [64]:
ypred

array([-2.92543453e+218, -2.90897068e+218, -2.89481074e+218, ...,
       -2.90582609e+218, -2.91060060e+218, -2.93148950e+218])

In [66]:
np.savetxt("y_pred3.csv",(ypred),fmt = '%1.2f')