In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression


In [2]:
x=np.loadtxt("train2.csv",delimiter=",")

In [3]:
x.shape , x

((379, 14), array([[-0.40784991, -0.48772236, -1.2660231 , ...,  0.41057102,
         -1.09799011, 37.9       ],
        [-0.40737368, -0.48772236,  0.24705682, ...,  0.29116915,
         -0.52047412, 21.4       ],
        [ 0.1251786 , -0.48772236,  1.01599907, ..., -3.79579542,
          0.89107588, 12.7       ],
        ...,
        [-0.40831101, -0.48772236,  0.24705682, ...,  0.33206621,
         -0.33404299, 20.8       ],
        [-0.41061997, -0.48772236, -1.15221381, ...,  0.203235  ,
         -0.74475218, 22.6       ],
        [ 0.34290895, -0.48772236,  1.01599907, ...,  0.38787479,
         -1.35871335, 50.        ]]))

In [4]:
x_train=x[:,:-1]
y_train=x[:,-1:]
x_train.shape, y_train.shape

((379, 13), (379, 1))

In [5]:
x_train

array([[-0.40784991, -0.48772236, -1.2660231 , ..., -0.30309415,
         0.41057102, -1.09799011],
       [-0.40737368, -0.48772236,  0.24705682, ...,  0.1130321 ,
         0.29116915, -0.52047412],
       [ 0.1251786 , -0.48772236,  1.01599907, ...,  0.80657583,
        -3.79579542,  0.89107588],
       ...,
       [-0.40831101, -0.48772236,  0.24705682, ...,  0.1130321 ,
         0.33206621, -0.33404299],
       [-0.41061997, -0.48772236, -1.15221381, ..., -0.71922039,
         0.203235  , -0.74475218],
       [ 0.34290895, -0.48772236,  1.01599907, ...,  0.80657583,
         0.38787479, -1.35871335]])

In [38]:
y_train

array([[346.],
       [104.],
       [ 49.],
       [180.],
       [110.],
       [ 72.],
       [ 68.],
       [216.],
       [ 47.],
       [296.],
       [ 65.],
       [ 96.],
       [ 67.],
       [ 52.],
       [100.],
       [202.],
       [128.],
       [ 63.],
       [281.],
       [152.],
       [124.],
       [245.],
       [101.],
       [113.],
       [ 48.],
       [197.],
       [186.],
       [132.],
       [245.],
       [ 91.],
       [ 43.],
       [101.],
       [111.],
       [199.],
       [220.],
       [281.],
       [217.],
       [ 93.],
       [174.],
       [150.],
       [206.],
       [ 61.],
       [ 55.],
       [118.],
       [ 53.],
       [275.],
       [215.],
       [142.],
       [ 90.],
       [ 65.],
       [200.],
       [ 96.],
       [249.],
       [200.],
       [155.],
       [170.],
       [141.],
       [179.],
       [225.],
       [ 61.],
       [103.],
       [131.],
       [158.],
       [275.],
       [246.],
       [ 97.],
       [30

In [6]:
x_test=np.loadtxt("test2.csv", delimiter=",")

In [7]:
x_test.shape

(127, 13)

In [8]:
alg=LinearRegression()

In [9]:
alg.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [10]:
y_pred=alg.predict(x_test)


In [11]:
y_pred

array([[12.43328344],
       [29.03367318],
       [22.37164455],
       [24.47778655],
       [20.60166977],
       [ 2.72533175],
       [30.40000409],
       [24.86120042],
       [18.65724977],
       [23.53985838],
       [24.11396872],
       [17.71143854],
       [17.44000298],
       [21.65356278],
       [42.31137694],
       [23.84974493],
       [24.47573232],
       [27.53872655],
       [20.23606694],
       [31.15155453],
       [23.78237904],
       [25.00979443],
       [33.95768541],
       [36.43515649],
       [32.04098329],
       [16.71322632],
       [23.47176611],
       [32.93828009],
       [25.1807008 ],
       [33.71008685],
       [16.88580202],
       [26.02760837],
       [23.27040025],
       [25.47758968],
       [15.00946631],
       [29.5857494 ],
       [26.24821245],
       [20.37245654],
       [24.43681498],
       [ 9.44706894],
       [ 8.38096654],
       [29.01392345],
       [29.59085403],
       [19.7575697 ],
       [20.3719679 ],
       [ 3

In [12]:
y_pred.shape

(127, 1)

In [14]:
import pandas as pd

In [16]:
yo=pd.DataFrame(y_pred)
yo.round(5)
yo.to_csv("pred5.csv")

In [17]:
y_pred1=alg.predict(x_train)


In [18]:
y_pred.shape

(127, 1)